In [2]:
import pandas as pd

# Load datasets
estimated = pd.read_csv('estimated_numbers.csv')
reported = pd.read_csv('reported_numbers.csv')
incidence = pd.read_csv('incidence_per_1000_pop_at_risk.csv')

# Merge Datasets on Country, Year, and WHO Region

# Merge estimated + reported
merged = estimated.merge(reported, on=["Country", "Year", "WHO Region"], suffixes=('_estimated', '_reported'))

# Merge with incidence data
merged = merged.merge(incidence, on=["Country", "Year", "WHO Region"])

# Drop exact duplicate rows
merged.drop_duplicates(inplace=True)

# Filter where WHO Region is 'Africa'
africa_df = merged[merged["WHO Region"] == "Africa"].copy()

# Fill missing min/max cases and deaths using the median values
africa_df['No. of cases_min'] = africa_df['No. of cases_min'].fillna(africa_df['No. of cases_median'])
africa_df['No. of cases_max'] = africa_df['No. of cases_max'].fillna(africa_df['No. of cases_median'])
africa_df['No. of deaths_min'] = africa_df['No. of deaths_min'].fillna(africa_df['No. of deaths_median'])
africa_df['No. of deaths_max'] = africa_df['No. of deaths_max'].fillna(africa_df['No. of deaths_median'])

# Fill missing reported cases/deaths with 0 (assumes underreporting)
africa_df['No. of cases_reported'] = africa_df['No. of cases_reported'].fillna(0)
africa_df['No. of deaths_reported'] = africa_df['No. of deaths_reported'].fillna(0)

# Save cleaned African malaria data to CSV
africa_df.to_csv('malaria_africa_cleaned.csv', index=False)

# View a few rows of the final dataset
africa_df.head()

,Country,Year,No. of cases_estimated,No. of deaths_estimated,No. of cases_median,No. of cases_min,No. of cases_max,No. of deaths_median,No. of deaths_min,No. of deaths_max,WHO Region,No. of cases_reported,No. of deaths_reported,No. of cases
1,Algeria,2017,0,0,0,0.0,0.0,0,0.0,0.0,Africa,0.0,0.0,0.00
2,Angola,2017,4615605[3106000-6661000],13316[9970-16600],4615605,3106000.0,6661000.0,13316,9970.0,16600.0,Africa,3874892.0,13967.0,228.91
8,Benin,2017,4111699[2774000-6552000],7328[5740-8920],4111699,2774000.0,6552000.0,7328,5740.0,8920.0,Africa,1573163.0,2182.0,399.56
11,Botswana,2017,2989[2300-4200],7[0-20],2989,2300.0,4200.0,7,0.0,20.0,Africa,1900.0,17.0,2.05
13,Burkina Faso,2017,7907562[5645000-11330000],27791[25100-30500],7907562,5645000.0,11330000.0,27791,25100.0,30500.0,Africa,10225459.0,4144.0,399.94